from dataclasses import dataclass, field
from typing import List


@dataclass(frozen=True)
class ColumnDef:
    name: str
    width: int


@dataclass(frozen=True)
class CCLFFileDef:
    table_name: str
    filename_pattern: str
    columns: List[ColumnDef]
    has_header: bool = False


CCLF_FILE_DEFS: List[CCLFFileDef] = [
    CCLFFileDef(
        table_name="parta_claims_header",
        filename_pattern="ZC1",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("PRVDR_OSCAR_NUM", 6),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("CLM_BILL_FAC_TYPE_CD", 1),
            ColumnDef("CLM_BILL_CLSFCTN_CD", 1),
            ColumnDef("PRNCPL_DGNS_CD", 7),
            ColumnDef("ADMTG_DGNS_CD", 7),
            ColumnDef("CLM_MDCR_NPMT_RSN_CD", 2),
            ColumnDef("CLM_PMT_AMT", 17),
            ColumnDef("CLM_NCH_PRMRY_PYR_CD", 1),
            ColumnDef("PRVDR_FAC_FIPS_ST_CD", 2),
            ColumnDef("BENE_PTNT_STUS_CD", 2),
            ColumnDef("DGNS_DRG_CD", 4),
            ColumnDef("CLM_OP_SRVC_TYPE_CD", 1),
            ColumnDef("FAC_PRVDR_NPI_NUM", 10),
            ColumnDef("OPRTG_PRVDR_NPI_NUM", 10),
            ColumnDef("ATNDG_PRVDR_NPI_NUM", 10),
            ColumnDef("OTHR_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_ADJSMT_TYPE_CD", 2),
            ColumnDef("CLM_EFCTV_DT", 10),
            ColumnDef("CLM_IDR_LD_DT", 10),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("CLM_ADMSN_TYPE_CD", 2),
            ColumnDef("CLM_ADMSN_SRC_CD", 2),
            ColumnDef("CLM_BILL_FREQ_CD", 1),
            ColumnDef("CLM_QUERY_CD", 1),
            ColumnDef("DGNS_PRCDR_ICD_IND", 1),
            ColumnDef("CLM_MDCR_INSTNL_TOT_CHRG_AMT", 15),
            ColumnDef("CLM_MDCR_IP_PPS_CPTL_IME_AMT", 15),
            ColumnDef("CLM_OPRTNL_IME_AMT", 22),
            ColumnDef("CLM_MDCR_IP_PPS_DSPRPRTNT_AMT", 15),
            ColumnDef("CLM_HIPPS_UNCOMPD_CARE_AMT", 15),
            ColumnDef("CLM_OPRTNL_DSPRPRTNT_AMT", 22),
            ColumnDef("CLM_BLG_PRVDR_OSCAR_NUM", 20),
            ColumnDef("CLM_BLG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_OPRTG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_ATNDG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_OTHR_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_CNTL_NUM", 40),
            ColumnDef("CLM_ORG_CNTL_NUM", 40),
            ColumnDef("CLM_CNTRCTR_NUM", 5),
        ],
    ),
    CCLFFileDef(
        table_name="parta_claims_revenue_center_detail",
        filename_pattern="ZC2",
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("CLM_LINE_NUM", 10),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_LINE_FROM_DT", 10),
            ColumnDef("CLM_LINE_THRU_DT", 10),
            ColumnDef("CLM_LINE_PROD_REV_CTR_CD", 4),
            ColumnDef("CLM_LINE_INSTNL_REV_CTR_DT", 10),
            ColumnDef("CLM_LINE_HCPCS_CD", 5),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("PRVDR_OSCAR_NUM", 6),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("CLM_LINE_SRVC_UNIT_QTY", 24),
            ColumnDef("CLM_LINE_CVRD_PD_AMT", 17),
            ColumnDef("HCPCS_1_MDFR_CD", 2),
            ColumnDef("HCPCS_2_MDFR_CD", 2),
            ColumnDef("HCPCS_3_MDFR_CD", 2),
            ColumnDef("HCPCS_4_MDFR_CD", 2),
            ColumnDef("HCPCS_5_MDFR_CD", 2),
            ColumnDef("CLM_REV_APC_HIPPS_CD", 5),
            ColumnDef("CLM_FAC_PRVDR_OSCAR_NUM", 20),
        ],
    ),
    CCLFFileDef(
        table_name="parta_procedure_code",
        filename_pattern="ZC3",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_VAL_SQNC_NUM", 2),
            ColumnDef("CLM_PRCDR_CD", 7),
            ColumnDef("CLM_PRCDR_PRFRM_DT", 10),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("PRVDR_OSCAR_NUM", 6),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("DGNS_PRCDR_ICD_IND", 1),
            ColumnDef("CLM_BLG_PRVDR_OSCAR_NUM", 20),
        ],
    ),
    CCLFFileDef(
        table_name="parta_diagnosis_code",
        filename_pattern="ZC4",
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_PROD_TYPE_CD", 1),
            ColumnDef("CLM_VAL_SQNC_NUM", 2),
            ColumnDef("CLM_DGNS_CD", 7),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("PRVDR_OSCAR_NUM", 6),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("CLM_POA_IND", 7),
            ColumnDef("DGNS_PRCDR_ICD_IND", 1),
            ColumnDef("CLM_BLG_PRVDR_OSCAR_NUM", 20),
        ],
    ),
    CCLFFileDef(
        table_name="partb_physicians",
        filename_pattern="ZC5",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("CLM_LINE_NUM", 10),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("RNDRG_PRVDR_TYPE_CD", 3),
            ColumnDef("RNDRG_PRVDR_FIPS_ST_CD", 2),
            ColumnDef("CLM_PRVDR_SPCLTY_CD", 2),
            ColumnDef("CLM_FED_TYPE_SRVC_CD", 1),
            ColumnDef("CLM_POS_CD", 2),
            ColumnDef("CLM_LINE_FROM_DT", 10),
            ColumnDef("CLM_LINE_THRU_DT", 10),
            ColumnDef("CLM_LINE_HCPCS_CD", 5),
            ColumnDef("CLM_LINE_CVRD_PD_AMT", 15),
            ColumnDef("CLM_LINE_PRMRY_PYR_CD", 1),
            ColumnDef("CLM_LINE_DGNS_CD", 7),
            ColumnDef("CLM_RNDRG_PRVDR_TAX_NUM", 10),
            ColumnDef("RNDRG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_CARR_PMT_DNL_CD", 2),
            ColumnDef("CLM_PRCSG_IND_CD", 2),
            ColumnDef("CLM_ADJSMT_TYPE_CD", 2),
            ColumnDef("CLM_EFCTV_DT", 10),
            ColumnDef("CLM_IDR_LD_DT", 10),
            ColumnDef("CLM_CNTL_NUM", 40),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("CLM_LINE_ALOWD_CHRG_AMT", 17),
            ColumnDef("CLM_LINE_SRVC_UNIT_QTY", 24),
            ColumnDef("HCPCS_1_MDFR_CD", 2),
            ColumnDef("HCPCS_2_MDFR_CD", 2),
            ColumnDef("HCPCS_3_MDFR_CD", 2),
            ColumnDef("HCPCS_4_MDFR_CD", 2),
            ColumnDef("HCPCS_5_MDFR_CD", 2),
            ColumnDef("CLM_DISP_CD", 2),
            ColumnDef("CLM_DGNS_1_CD", 7),
            ColumnDef("CLM_DGNS_2_CD", 7),
            ColumnDef("CLM_DGNS_3_CD", 7),
            ColumnDef("CLM_DGNS_4_CD", 7),
            ColumnDef("CLM_DGNS_5_CD", 7),
            ColumnDef("CLM_DGNS_6_CD", 7),
            ColumnDef("CLM_DGNS_7_CD", 7),
            ColumnDef("CLM_DGNS_8_CD", 7),
            ColumnDef("DGNS_PRCDR_ICD_IND", 1),
            ColumnDef("CLM_DGNS_9_CD", 7),
            ColumnDef("CLM_DGNS_10_CD", 7),
            ColumnDef("CLM_DGNS_11_CD", 7),
            ColumnDef("CLM_DGNS_12_CD", 7),
            ColumnDef("HCPCS_BETOS_CD", 3),
            ColumnDef("CLM_RNDRG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_RFRG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_CNTRCTR_NUM", 5),
        ],
    ),
    CCLFFileDef(
        table_name="partb_dme",
        filename_pattern="ZC6",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("CLM_LINE_NUM", 10),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_FROM_DT", 10),
            ColumnDef("CLM_THRU_DT", 10),
            ColumnDef("CLM_FED_TYPE_SRVC_CD", 1),
            ColumnDef("CLM_POS_CD", 2),
            ColumnDef("CLM_LINE_FROM_DT", 10),
            ColumnDef("CLM_LINE_THRU_DT", 10),
            ColumnDef("CLM_LINE_HCPCS_CD", 5),
            ColumnDef("CLM_LINE_CVRD_PD_AMT", 15),
            ColumnDef("CLM_PRMRY_PYR_CD", 1),
            ColumnDef("PAYTO_PRVDR_NPI_NUM", 10),
            ColumnDef("ORDRG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_CARR_PMT_DNL_CD", 2),
            ColumnDef("CLM_PRCSG_IND_CD", 2),
            ColumnDef("CLM_ADJSMT_TYPE_CD", 2),
            ColumnDef("CLM_EFCTV_DT", 10),
            ColumnDef("CLM_IDR_LD_DT", 10),
            ColumnDef("CLM_CNTL_NUM", 40),
            ColumnDef("BENE_EQTBL_BIC_HICN_NUM", 11),
            ColumnDef("CLM_LINE_ALOWD_CHRG_AMT", 17),
            ColumnDef("CLM_DISP_CD", 2),
            ColumnDef("CLM_BLG_PRVDR_NPI_NUM", 10),
            ColumnDef("CLM_RFRG_PRVDR_NPI_NUM", 10),
        ],
    ),
    CCLFFileDef(
        table_name="partd_claims",
        filename_pattern="ZC7",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_LINE_NDC_CD", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_LINE_FROM_DT", 10),
            ColumnDef("PRVDR_SRVC_ID_QLFYR_CD", 2),
            ColumnDef("CLM_SRVC_PRVDR_GNRC_ID_NUM", 20),
            ColumnDef("CLM_DSPNSNG_STUS_CD", 1),
            ColumnDef("CLM_DAW_PROD_SLCTN_CD", 1),
            ColumnDef("CLM_LINE_SRVC_UNIT_QTY", 24),
            ColumnDef("CLM_LINE_DAYS_SUPLY_QTY", 9),
            ColumnDef("PRVDR_PRSBNG_ID_QLFYR_CD", 2),
            ColumnDef("BLANK", 20),
            ColumnDef("CLM_LINE_BENE_PMT_AMT", 13),
            ColumnDef("CLM_ADJSMT_TYPE_CD", 2),
            ColumnDef("CLM_EFCTV_DT", 10),
            ColumnDef("CLM_IDR_LD_DT", 10),
            ColumnDef("CLM_LINE_RX_SRVC_RFRNC_NUM", 12),
            ColumnDef("CLM_LINE_RX_FILL_NUM", 9),
            ColumnDef("CLM_PHRMCY_SRVC_TYPE_CD", 2),
            ColumnDef("CLM_PRSBNG_PRVDR_GNRC_ID_NUM", 35),
        ],
    ),
    CCLFFileDef(
        table_name="beneficiary_demographics",
        filename_pattern="ZC8",
        columns=[
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("BENE_FIPS_STATE_CD", 2),
            ColumnDef("BENE_FIPS_CNTY_CD", 3),
            ColumnDef("BENE_ZIP_CD", 5),
            ColumnDef("BENE_DOB", 10),
            ColumnDef("BENE_SEX_CD", 1),
            ColumnDef("BENE_RACE_CD", 1),
            ColumnDef("BENE_AGE", 3),
            ColumnDef("BENE_MDCR_STUS_CD", 2),
            ColumnDef("BENE_DUAL_STUS_CD", 2),
            ColumnDef("BENE_DEATH_DT", 10),
            ColumnDef("BENE_RNG_BGN_DT", 10),
            ColumnDef("BENE_RNG_END_DT", 10),
            ColumnDef("BENE_1ST_NAME", 30),
            ColumnDef("BENE_MIDL_NAME", 15),
            ColumnDef("BENE_LAST_NAME", 40),
            ColumnDef("BENE_ORGNL_ENTLMT_RSN_CD", 1),
            ColumnDef("BENE_ENTLMT_BUYIN_IND", 1),
            ColumnDef("BENE_PART_A_ENRLMT_BGN_DT", 10),
            ColumnDef("BENE_PART_B_ENRLMT_BGN_DT", 10),
            ColumnDef("BENE_LINE_1_ADR", 45),
            ColumnDef("BENE_LINE_2_ADR", 45),
            ColumnDef("BENE_LINE_3_ADR", 40),
            ColumnDef("BENE_LINE_4_ADR", 40),
            ColumnDef("BENE_LINE_5_ADR", 40),
            ColumnDef("BENE_LINE_6_ADR", 40),
            ColumnDef("GEO_ZIP_PLC_NAME", 100),
            ColumnDef("GEO_USPS_STATE_CD", 2),
            ColumnDef("GEO_ZIP5_CD", 5),
            ColumnDef("GEO_ZIP4_CD", 4),
        ],
    ),
    CCLFFileDef(
        table_name="beneficiary_xref",
        filename_pattern="ZC9",
        has_header=False,
        columns=[
            ColumnDef("HICN_MBI_XREF_IND", 1),
            ColumnDef("CRNT_NUM", 11),
            ColumnDef("PRVS_NUM", 11),
            ColumnDef("PRVS_ID_EFCTV_DT", 10),
            ColumnDef("PRVS_ID_OBSLT_DT", 10),
            ColumnDef("BENE_RRB_NUM", 12),
        ],
    ),
    CCLFFileDef(
        table_name="claims_benefit_enhancement_and_demonstration_code_file_cclfa",
        filename_pattern="ZCA",
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_ACTV_CARE_FROM_DT", 10),
            ColumnDef("CLM_NGACO_PBPMT_SW", 1),
            ColumnDef("CLM_NGACO_PDSCHRG_HCBS_SW", 1),
            ColumnDef("CLM_NGACO_SNF_WVR_SW", 1),
            ColumnDef("CLM_NGACO_TLHLTH_SW", 1),
            ColumnDef("CLM_NGACO_CPTATN_SW", 1),
            ColumnDef("CLM_DEMO_1ST_NUM", 2),
            ColumnDef("CLM_DEMO_2ND_NUM", 2),
            ColumnDef("CLM_DEMO_3RD_NUM", 2),
            ColumnDef("CLM_DEMO_4TH_NUM", 2),
            ColumnDef("CLM_DEMO_5TH_NUM", 2),
            ColumnDef("CLM_PBP_INCLSN_AMT", 19),
            ColumnDef("CLM_PBP_RDCTN_AMT", 19),
            ColumnDef("CLM_NGACO_CMG_WVR_SW", 1),
            ColumnDef("CLM_INSTNL_PER_DIEM_AMT", 19),
            ColumnDef("CLM_MDCR_IP_BENE_DDCTBL_AMT", 15),
            ColumnDef("CLM_MDCR_COINSRNC_AMT", 19),
            ColumnDef("CLM_BLOOD_LBLTY_AMT", 15),
            ColumnDef("CLM_INSTNL_PRFNL_AMT", 15),
            ColumnDef("CLM_NCVRD_CHRG_AMT", 19),
            ColumnDef("CLM_MDCR_DDCTBL_AMT", 19),
            ColumnDef("CLM_RLT_COND_CD", 2),
            ColumnDef("CLM_OPRTNL_OUTLR_AMT", 19),
            ColumnDef("CLM_MDCR_NEW_TECH_AMT", 19),
            ColumnDef("CLM_ISLET_ISOLN_AMT", 19),
            ColumnDef("CLM_SQSTRTN_RDCTN_AMT", 19),
            ColumnDef("CLM_1_REV_CNTR_ANSI_RSN_CD", 3),
            ColumnDef("CLM_1_REV_CNTR_ANSI_GRP_CD", 2),
            ColumnDef("CLM_MIPS_PMT_AMT", 19),
        ],
    ),
    CCLFFileDef(
        table_name="cclfb_claims_benefit_enhancement_and_demonstration_code_file_cclfb",
        filename_pattern="ZCB",
        has_header=False,
        columns=[
            ColumnDef("CUR_CLM_UNIQ_ID", 13),
            ColumnDef("CLM_LINE_NUM", 10),
            ColumnDef("BENE_MBI_ID", 11),
            ColumnDef("BENE_HIC_NUM", 11),
            ColumnDef("CLM_TYPE_CD", 2),
            ColumnDef("CLM_NGACO_PBPMT_SW", 1),
            ColumnDef("CLM_NGACO_PDSCHRG_HCBS_SW", 1),
            ColumnDef("CLM_NGACO_SNF_WVR_SW", 1),
            ColumnDef("CLM_NGACO_TLHLTH_SW", 1),
            ColumnDef("CLM_NGACO_CPTATN_SW", 1),
            ColumnDef("CLM_DEMO_1ST_NUM", 2),
            ColumnDef("CLM_DEMO_2ND_NUM", 2),
            ColumnDef("CLM_DEMO_3RD_NUM", 2),
            ColumnDef("CLM_DEMO_4TH_NUM", 2),
            ColumnDef("CLM_DEMO_5TH_NUM", 2),
            ColumnDef("CLM_PBP_INCLSN_AMT", 19),
            ColumnDef("CLM_PBP_RDCTN_AMT", 19),
            ColumnDef("CLM_NGACO_CMG_WVR_SW", 1),
            ColumnDef("CLM_INSTNL_PER_DIEM_AMT", 19),
            ColumnDef("CLM_MDCR_IP_BENE_DDCTBL_AMT", 15),
            ColumnDef("CLM_MDCR_COINSRNC_AMT", 19),
            ColumnDef("CLM_BLOOD_LBLTY_AMT", 15),
            ColumnDef("CLM_INSTNL_PRFNL_AMT", 15),
            ColumnDef("CLM_NCVRD_CHRG_AMT", 19),
            ColumnDef("CLM_MDCR_DDCTBL_AMT", 19),
            ColumnDef("CLM_RLT_COND_CD", 2),
            ColumnDef("CLM_OPRTNL_OUTLR_AMT", 19),
            ColumnDef("CLM_MDCR_NEW_TECH_AMT", 19),
            ColumnDef("CLM_ISLET_ISOLN_AMT", 19),
            ColumnDef("CLM_SQSTRTN_RDCTN_AMT", 19),
            ColumnDef("CLM_1_REV_CNTR_ANSI_RSN_CD", 3),
            ColumnDef("CLM_1_REV_CNTR_ANSI_GRP_CD", 2),
            ColumnDef("CLM_MIPS_PMT_AMT", 19),
        ],
    ),
    CCLFFileDef(
        table_name="CCLF0_SUMMARY_STATS_HEADER_RECORD",
        filename_pattern="ZC0",
        has_header=True,
        columns=[
            ColumnDef("FILE_NUMBER_LABEL", 7),
            ColumnDef("DELIMITER", 1),
            ColumnDef("FILE_DESCRIPTION_LABEL", 43),
            ColumnDef("DELIMITER", 1),
            ColumnDef("TOTAL_RECORDS_COUNT_LABEL", 11),
            ColumnDef("DELIMITER", 1),
            ColumnDef("RECORD_LENGTH_LABEL", 5),
        ],
    ),
]
